version: '3'

services:
  nginx-flv-rtmp:
    build: .
    container_name: rtmp_server
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935

